Feat: Layout
Undecided-Discord/site pull request #13
Opened 2022-02-20 09:14 UTC by Yusuke4869

Closes #9 #10 

ヘッダー、フッター

2022-02-21 13:35 UTC, laminne requested changes
レイアウトの完成イメージの画像をつけてください

2022-02-21 14:02 UTC, Yusuke4869 commented
> レイアウトの完成イメージの画像をつけてください

PC
![image](https://user-images.githubusercontent.com/67366917/154969700-4abc171d-23cf-4d71-8d55-29902680eea8.png)

スマホ
![image](https://user-images.githubusercontent.com/67366917/154969773-829d5562-c120-4be8-8574-0c1f2e0abbbb.png)

スマホメニュー
![image](https://user-images.githubusercontent.com/67366917/154969876-6d7a32f9-6a92-4c26-8434-904d39d75293.png)

2022-02-21 14:03 UTC, laminne commented
スマホメニューの部分が崩れてるけどこれはいいのか...?

2022-06-12 02:16 UTC, Yusuke4869 commented
ハンバーガーメニューは削除しました（別で実装してもらいます）

2022-06-12 03:40 UTC, laminne approved these changes
致命的な間違いはなさそうです.

2022-06-12 03:52 UTC, re-taro approved these changes

2022-06-12 04:03 UTC, merged