Feat: index
Undecided-Discord/site pull request #16
Opened 2022-06-19 21:49 UTC by Yusuke4869

Closes #3

2022-06-20 13:15 UTC, YukiYuigishi commented
![image](https://user-images.githubusercontent.com/64316110/174609797-a3cc6094-d7ba-4446-be75-36d3a1b0a081.png)
![image](https://user-images.githubusercontent.com/64316110/174609855-8fdebfaf-2a45-4503-9b9b-45cc60b2b0ce.png)

2022-06-20 13:16 UTC, YukiYuigishi commented
![image](https://user-images.githubusercontent.com/64316110/174610083-32e1c23c-bda2-4ad1-8be3-c8f9c5aaf0f4.png)

2022-06-20 13:21 UTC, YukiYuigishi commented
失敗例
![image](https://user-images.githubusercontent.com/64316110/174611083-a98f070d-cae2-4359-868e-8544dab73a2d.png)

2022-06-21 13:44 UTC, laminne commented on src/components/QA.tsx
> +  for (let i = 0; i < (answerPlanes.length ?? 0) + (answerLinks?.length ?? 0); i += 1) {
```suggestion
  for (let i = 0; i < answerPlanes.length + answerLinks?.length ; i += 1) {
```
`?? 0`する意味がない気がします

2022-06-21 13:44 UTC, laminne commented on src/components/QA.tsx
> +  for (let i = 0; i < (answerPlanes.length ?? 0) + (answerLinks?.length ?? 0); i += 1) {
```suggestion
  for (let i = 0; i < (answerPlanes.length ?? 0) + (answerLinks?.length ?? 0); i++) {
```
インクリメント使ってください....

2022-06-21 13:47 UTC, laminne requested changes

2022-06-21 13:47 UTC, laminne commented on src/components/QA.tsx
> +  for (let i = 0; i < (answerPlanes.length ?? 0) + (answerLinks?.length ?? 0); i += 1) {
ここ、nullableなのがアレなのでfor文回す前に処理できませんか...

2022-06-24 08:06 UTC, laminne submitted a review, later dismissed

2022-06-24 12:33 UTC, YukiYuigishi submitted a review, later dismissed

2022-06-24 12:33 UTC, YukiYuigishi commented on src/components/QA.tsx
> +  // テキストとリンクを交互に
もう少しContextをお願いします
anserListのexampleなんかがあるととても読みやすくなるので

2022-06-24 14:28 UTC, YukiYuigishi approved these changes

2022-06-24 22:23 UTC, laminne approved these changes

2022-06-24 22:23 UTC, merged